name: 🔎 Banner finder bug
description: Report issues encountered when finding a cookie banner
title: 🔎 [TITLE HERE]
labels:
  - "area: finding banners"
  - bug
body:
  - type: input
    attributes:
      label: Website address
      description: The URL you encountered this problem on
      placeholder: https://example.com
    validations:
      required: true
  - type: input
    attributes:
      label: Resolution
      description: The resolution you used for the analysis
      placeholder: 1920x1080
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Device mode
      description: The device mode you used for the analysis
      options:
        - Desktop
        - Mobile
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: >-
        Explain your problem as clearly as possible. What happened? What did you
        expect to happen? Screenshots are encouraged!
      placeholder: |
        I expected ...

        What happened instead was ...

        Screenshots:
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Can it be consistently reproduced?
      description: How often does the error happen when you try to reproduce it?
      options:
        - it happens every time (100%)
        - it happens sometimes (1-99%)
        - can not reproduce it again (0%)
    validations:
      required: true
